if(LIBQDARK_INCLUDE_DIR AND LIBQDARK_LIBRARY)
	set(LIBQDARK_QUIETLY TRUE)
endif(LIBQDARK_INCLUDE_DIR AND LIBQDARK_LIBRARY)

find_library(LIBQDARK_LIBRARY libqdark)

find_path(LIBQDARK_INCLUDE_DIR QDarkThemePlugin.h)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBQDARK DEFAULT_MSG LIBQDARK_LIBRARY LIBQDARK_INCLUDE_DIR)

MARK_AS_ADVANCED(
	LIBQDARK_INCLUDE_DIR
	LIBQDARK_LIBRARY
)
